spring.application.name=bff-agendadortarefas

server.port=8084

usuario.url = localhost:8081/usuario
agendador-tarefas.url = localhost:8082/tarefas
notificador.url = localhost:8083/email

cron.horario = 0 0/1 * * * ?

usuario.email = admin@admin.com
usuario.senha = 1234
